### ISSUE TITLE
Issue with missing fields

### ISSUE THREAD

**Issue by karenlfisher** [lddweb/ldd-directory-lite#124]
I have been using your LDD Directory Lite plugin very happily at https://lifelinedirectory.com/ for a while now and recently added the reports function too.

Today I cannot access/see any of the additional fields when adding or editing listings. Only name, description, summary, category, tags and logo are available now, so I cannot add address or contact details any more.  Front end is fine; no change.

Using:
WordPress - Version 6.0.3
LDD Directory Lite - Version 3.7
LDD Directory Reports - Version 0.4

Yours  hopefully
Karen Fisher 
![missing-fields](https://user-images.githubusercontent.com/116289382/196981627-c992b44c-1924-45a6-8ec2-3c0122140867.png)

**Comment by pixelpusherongit** [comment]
Same problem here. Running PHP 7.4.16

**Comment by pixelpusherongit** [comment]
Reverting to previous version 2.6.4 solved my issue. Waiting for developer to fix. You can download previous version by clicking the advanced view link on right side in wordpress.org LDD Directory Lite plugin page.

**Comment by karenlfisher** [comment]
Thank you pixelpusherongit!
I'm a self taught 'fly by the seat of my pants' gal and your response has solved the problem and made my day! It might be an obvious fix for many but wasn't for me, until now! x

**Comment by pixelpusherongit** [comment]
Also, You should be able to update to the latest 3.8 after you add your new data with the previous version. I kept a copy of the old on my server so I could roll backward - in case I need to add more listings before a fix is out.
