### ISSUE TITLE
Social Meta links

### ISSUE THREAD

**Issue by goodmuyis** [lddweb/ldd-directory-lite#17]
listing-meta

Their Links looks like this on single view: 
`<a href="facebook.com/goodmuyis"></a>
and will return something like this:
http://localhost/bizdir/listing/songa-firm/facebook.com/goodmuyis`

I think Protocol need to be appended so as to give proper link

Also it will be good if the Contact Listing owner remain in Lightbox or Ajax dropdown except for mobile view

**Comment by mwaterous** [comment]
Can I be removed from this issue?
