### ISSUE TITLE
Feature Request: Highlight featured listings

### ISSUE THREAD

**Issue by mcoville** [lddweb/ldd-directory-lite#30]
It would be helpful if we could adjust the background color of featured listings. Have featured listings show up at the top of the category list. Designate an icon that shows up on the listing when it is tagged featured. And any other way we could highlight featured listings.

This was also posted to the Wordpress support forum.

**Comment by LDDConsulting** [comment]
Added support for [featured listings](https://plugins.lddwebdesign.com/featured-listings/).
