### ISSUE TITLE
My listings are coming up with 404 errors

### ISSUE THREAD

**Issue by integritymcseo** [lddweb/ldd-directory-lite#31]
I just downloaded the plugin and I added my first listing. The listing is showing up as a 404 error http://recoveryfinder.net/listings/empathic-recovery/ Can you please help? Thank you.

**Comment by LDDConsulting** [comment]
Fixed #31 through the commits https://github.com/lddweb/ldd-directory-lite/commit/60c1623bd551bab321bcab59b9f99df6f38b5ea5 and https://github.com/lddweb/ldd-directory-lite/commit/788c3b910cab643b4200aee90cbde7c48de09f0a for 404 on installation and updating slug from LDD settings page.
