### ISSUE TITLE
Post not showing up on site

### ISSUE THREAD

**Issue by VaporVix** [lddweb/ldd-directory-lite#39]
I type up a whole listing and am able to preview it, but as soon as I submit it and try to look it up again to make sure it's working properly still it goes to a "page can't be found" page instead of the listing... I've been trying to get it to work all night and even deleted it and reinstalled it and still the same problem! Help please!! And thanks in advance!

**Comment by rahsico22** [comment]
LDDDavid......i tried what you did....and no it does not work....I have the same issue as VaporVix.....

**Comment by LDDConsulting** [comment]
This issue is resolved on latest current version. Please update you LDD Directory plugin to resolve this issue. Thanks.
