### ISSUE TITLE
Alphabetical listings

### ISSUE THREAD

**Issue by danhimes** [lddweb/ldd-directory-lite#40]
Hi there, love the plugin. I am using Version 0.8.4-beta. 
Two requests:
     1. Is is possible to show the listings alphabetically? The category view is great, but another option would be excellent.
     2. When viewing a category, the listings are from newest to oldest. What about an option to do alphabetical here?

Two things I noticed:
     1. When I installed the Taxonomy and Post Type slug were set to the same thing 'listings' and it caused an error until I changed one.
     2. The email contact form has all of the same labels "What is this in regards to?". Easily changed it, but it isn't make sense to me to have them all the same.

Thanks for your time and I apologize in advance if I made a mistake due to my limited knowledge. I am coming from a Drupal background and just getting the swing of things here. Thanks!

**Comment by LDDConsulting** [comment]
> 1. When I installed the Taxonomy and Post Type slug were set to the same thing 'listings' and it caused an error until I changed one.
> 2. The email contact form has all of the same labels "What is this in regards to?". Easily changed it, but it isn't make sense to me to have them all the same.

These issues fixed in stable release.

**Comment by LDDConsulting** [comment]
LDD Directory Lite plugin have option to [sort listings](https://plugins.lddwebdesign.com/listing-sort-options/).
