### ISSUE TITLE
Settings Fatal Error

### ISSUE THREAD

**Issue by kaniasty** [lddweb/ldd-directory-lite#43]
When I try to update settings, I get this error: 

Fatal error: Cannot unset string offsets in /usr/home/uxpaboston/public_html/uxpaboston_wp/wp-content/plugins/ldd-directory-lite/includes/admin/register-settings.php on line 326

Running Wordpress 4.1.1

**Comment by LDDConsulting** [comment]
Hi kaniasty, This issue is already resolved in current version. Please update it to latest version. Thanks.
