### ISSUE TITLE
Apologies, but the page you requested could not be found. Perhaps searching will help.

### ISSUE THREAD

**Issue by linksmarketinggroup** [lddweb/ldd-directory-lite#45]
I installed your LDD Directory Lite plug-in. I created a category and then a listing in that category with info and photos, etc. When I go into the business directory and click on the category, the listing shows the search info but when I click on the listing link to see the photos and more detailed listing info, the fallowing is displayed:

Apologies, but the page you requested could not be found. Perhaps searching will help.

**Comment by LDDConsulting** [comment]
Hi linksmarketinggroup, This issue is already resolved in your version. Please update to latest version to resolve this issue. Thanks.
