### ISSUE TITLE
Error 404. Page not found!

### ISSUE THREAD

**Issue by Tunnelvine** [lddweb/ldd-directory-lite#47]
I've noticed others with this problem after entering a listing and clicking on the link it takes you to Error 404. Page not found! I've tried reinstalling the plug in many times and even tried reinstalling WordPress, which didn't resolve the issue. 

After a fresh install, entering a TEST LISTING, and clicking the directory menu bar..., /directory - it will show the "test listing" under the categories. When clicking the individual "title of the test listing" it will take you to the proper file /listing/ and actually show the test entry url in the browser. However, the page that it shows at YOURWEBSITE.COM/listing/testlisting is "Error 404. Page nor found".

Has anyone posted an issue fix to this? The older post shows it was resolved, but I could not find the how to fix post. Thanks for any help to this..., looks like a nice database plug in if I can get it to work.

**Comment by javedakhtar1985** [comment]
Hello,

I am also having the same problem. can anyone help on this Please?

http://dev.mspalliance.com/listing/partner-4/

**Comment by LDDConsulting** [comment]
Hello guys,

For resolving this 404 issue, please go to **directory -> settings** from wordpress admin section and change these two fields,

>Taxonomy Slug = listings
>Post Type Slug = listing

save changes and go to **settings -> permalinks** and just press "**Save Changes**" button so that your site's rules are refreshed once. After that check if 404 issue is gone. Thanks.

**Comment by davenir** [comment]
Thanks - this worked perfectly for me
