### ISSUE TITLE
Oops! That page can’t be found.

### ISSUE THREAD

**Issue by RachelWooster** [lddweb/ldd-directory-lite#48]
When I click on the business being listed I get the following error "Oops! That page can’t be found."

This is the page the business is on that I am clicking on
http://mountainbulletin.com/listings/auto-repair/

This is the link it should be going to but gives me "Oops! That page can’t be found."
http://mountainbulletin.com/listings/george-galts-mobile-repair-service/

**Comment by LDDConsulting** [comment]
Hi RachelWooste, This issue is already resolved in current version.
