### ISSUE TITLE
Bootstrap (Link Color)

### ISSUE THREAD

**Issue by Micd1** [lddweb/ldd-directory-lite#53]
Hi Guys,

I have an issue with bootstrap on a website that is being designed. When left enabled, all the links on the website turn blue and only change to the default black color when you click on them.
On the other hand, when bootstrap is disabled the colors work out fine - but this time messing up the nice look of the directory on the directory page.
Your assistance will be much appreciated.

**Comment by LDDConsulting** [comment]
Hi Micd1, 
Blue is the default color for links in bootstrap. You can change them using custom css.

.directory-lite a{
    color: #428bca;
}
