### ISSUE TITLE
Mobile responsive navigation menu

### ISSUE THREAD

**Issue by chrisfosterwebdesign** [lddweb/ldd-directory-lite#55]
I like the "look and feel" of the directory, however when the plug-in is activated, the mobile responsive menu of my theme is no longer visible and visitors cannot navigate the site on smartphones http://grandblancchamber.com/
Please provide a fix ASAP. Thanks
Chris

**Comment by LDDConsulting** [comment]
This is purely theme issue, as plugin mobile menu work well with WordPress default themes.

**Comment by chrisfosterwebdesign** [comment]
Who and what is this?


      Best Regards -

     248.933.6235
     chrisfosterwebdesign.com
