### ISSUE TITLE
Initial email not sending

### ISSUE THREAD

**Issue by AnthonyJohn21** [lddweb/ldd-directory-lite#57]
When a user registers for the first time they are not receiving the email that should have their login information. The only way for them to get it is to say that they lost their password even though they never got it in the first place. Also, when finally getting the login via 'lost password' there is no way for them to log out. Am I missing something or did I not set up something correctly?

**Comment by LDDConsulting** [comment]
There is some issue at your end as when you register from frontend, you should receive email with username and password link to generate password. 

I suggest to install the [SMTP plugin](https://wordpress.org/plugins/wp-mail-smtp/) and send the test email to yourself.
