### ISSUE TITLE
Individual listings come up as page not found

### ISSUE THREAD

**Issue by rbirkin** [lddweb/ldd-directory-lite#59]
I've installed the LDD Directory and have entered a few listings, but when I click on the individual listing, it comes up as page not found.

It's automatically adding the slug /blog/listings-1/whatever the listing name is

Are you able to advise how I can rectify this?

**Comment by musamamasood** [comment]
> I've installed the LDD Directory and have entered a few listings, but when I click on the individual listing, it comes up as page not found.

Please navigate to **Settings -> Permalinks** and hit on **Save Changes**. 

> It's automatically adding the slug /blog/listings-1/whatever the listing name is

I suggest to fill out **Listing Name** first then it would generate the slug based on listing name. But you can also change the permalink slug by click on **edit button**.

**Comment by LDDConsulting** [comment]
> I've installed the LDD Directory and have entered a few listings, but when I click on the individual listing, it comes up as page not found.

Please navigate to Settings -> Permalinks and hit on Save Changes.

> It's automatically adding the slug /blog/listings-1/whatever the listing name is

I suggest to fill out Listing Name first then it would generate the slug based on listing name. But you can also change the permalink slug by click on edit button.
