### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by hanklu** [lddweb/ldd-directory-lite#70]
All of page is OK, but in follow page, footer will cover it.(PC only, cell phone view is OK)
Issue link:
https://blender.tw/listings/miscellaneous/

OK link:
https://blender.tw/directory/

theme: Smartline Lite version： 1.4.3

I change theme and close this issue

**Comment by LDDConsulting** [comment]
Okay, Let me know if you still need help and I can send over snippets to you.

We have released [LDD Directory Lite v1.1.0](https://github.com/lddweb/ldd-directory-lite/releases/tag/1.1.0) with support to customize template outer divs through hooks. 

You can find the sample code for [Divi Theme](https://gist.github.com/LDDConsulting/4ae25ee951ecb3ed60f9701f6ce8fbed). 

Thanks.
