### ISSUE TITLE
Shortcode showing all tags

### ISSUE THREAD

**Issue by wombizclub** [lddweb/ldd-directory-lite#73]
My directory shortcode is pulling through a long list of tags and categories from places other than the directory.  I only want to display the grid of the most recent 8 listings but not this long list of tags. Can you help please? [http://www.womensbusiness.club/directory](http://www.womensbusiness.club/directory)

**Comment by LDDConsulting** [comment]
Sure, Could you please elaborate more about issue which you are facing. Thanks

**Comment by wombizclub** [comment]
It was solved with the piece of css you sent me

Have a lovely day.
Angela

**Comment by wombizclub** [comment]
I am having the same problem again after doing updates. It must be a plugin
conflict. If you have the CSS to hand that you send previous can you resend
it? I have a back up but just want to double check that I have the correct
CSS

**Comment by LDDConsulting** [comment]
Here is that original thread, I believe.

https://wordpress.org/support/topic/pullings-tags-from-other-plugins/

All the template files found in`/ldd-directory-lite/templates` can be copied to a directory in your theme called lddlite_templates.

For example, if you need to edit `/wp-content/plugins/ldd-directory-lite/templates/category.php`, you can copy it to `/wp-content/themes/your-theme-directory/lddlite_templates/category.php`. While you can copy the entire directory verbatim, it is recommended that you only copy the files you need.

_This will ensure that your changes are not overwritten in the future._

**Comment by wombizclub** [comment]
Hi, I am terrible trouble with your plugin. Firstly the updates have really
messed my directory up and secondly I have just bought the review add on
but am having troulbe installing it.  It is showing error below:

The package could not be installed. No valid plugins were found.

Plugin install failed.

Return to Plugin Installer
<https://www.womensbusiness.club/wp-admin/plugin-install.php>
