### ISSUE TITLE
Show listings from specify category always goes to top of page

### ISSUE THREAD

**Issue by kentwelter** [lddweb/ldd-directory-lite#74]
No matter where I place the short code for showing a listing from a specific category, the listing goes to the top of the page below the header. I don't seem to have any control over where the show listing by category will appear on a page. It is always on the top.

Here is an example page:
https://www.willametteinnovators.com/directory/

With the following text and short code:

Mid-Willamette Valley Traded-Sector Companies
[directory]
[directory_category slug="traded-sector" view="compact" list_order_by="business_name" list_order="ASC" limit="8"]

Notice I have placed the show directory by category shortcode at the end of the input, but it shows up at the top.

**Comment by musamamasood** [comment]
First above example page showing 404. I have confuse about approach where two shortcodes placed at single page `[directory]` and `[directory_category slug="traded-sector" view="compact" list_order_by="business_name" list_order="ASC" limit="8"]`.

It would great if you explain more about issue which you are facing and share respective screentshot as well.

**Comment by LDDConsulting** [comment]
First above example page showing 404. I have confuse about approach where two shortcodes placed in page [directory] and [directory_category slug="traded-sector" view="compact" list_order_by="business_name" list_order="ASC" limit="8"].

It would great if you explain more about issue which you are facing and share respective screentshot as well.

**Comment by happyscribeme** [comment]
I have this question as well. I am using the shortcode:

[directory_category slug="affiliate" view="grid" list_order_by="title" list_order="ASC"]

And no matter where I place this shortcode, it shows up at the top of my page (above any content). I have tried placing this shortcode in the Classic editor and in the new block editor, but it doesn't matter - it will always appear at the top of the page.

When tested on other pages, the regular [directory] shortcode behaves as expected, but the directory_category shortcode will ONLY appear at the top of the page, no matter where it is placed relative to any other content on a page.
