### ISSUE TITLE
Gid view doesn't work

### ISSUE THREAD

**Issue by mediahuisvenray** [lddweb/ldd-directory-lite#79]
I got my directory plugin working on: http://culturavenray.nl/databank/dans/

1) my grid view doesn’t show.. anyone knows how i can fix this?

2) how can i change the backgroundcolor of the navigation bannner (where the search form is placed for example).

3) i got 404 when i go to the submit a listing and manage pages…. why…. any thoughts?

**Comment by LDDConsulting** [comment]
Discussed on support forum. 
https://wordpress.org/support/topic/grid-view-doesnt-show/
