### ISSUE TITLE
Error message "Sorry, User Registration on this site is currently disabled."  how do I enable it?

### ISSUE THREAD

**Issue by khinson6** [lddweb/ldd-directory-lite#81]
I looked over your documentation several times, have not seen anything that explains how to enable or disable "User Registration" on my site for the Submit Listing feature.

Ken Hinson

**Comment by LDDConsulting** [comment]
Good afternoon Ken. This is a WordPress setting that must be activated in order to use this feature of the plugin ( Dashboard >> Settings >> General ).

http://prntscr.com/euvpgv

**Comment by khinson6** [comment]
Works fine now, thanks for the quick response. I really love your plugin and your customer service. You've got me excited about an online directoy service again. THANKS!

**Comment by LDDConsulting** [comment]
You're welcome!
