### ISSUE TITLE
Emails: Visitor information not getting through to advertiser

### ISSUE THREAD

**Issue by islamiccenter** [lddweb/ldd-directory-lite#82]
Good morning. Please see the email we received below.

On Tue, Apr 11, 2017 at 3:14 PM, Tutorbees <info@tutorbees.com> wrote:
As-Salamu Aalaykum,

Thank you for following up. The information has been updated on the ICOI website and our ad is now running. 

I have a concern though: there is a contact form that is associated with our ad. The contact form allows individuals to contact us by entering their name, email, subject, and message. I completed the form to see what information is received on our end. The only information that we received were the sender's email as office@icoi.net, along with the subject line and the message. This means that the individual’s name and email that were submitted in the form were not included in the message received by us. My question is: can we fix this issue so we are able to identify the name and email of those who contact us? Otherwise, there is no way for us to know who contacted us nor will we be able to reply to submitted messages.

Jazakum Allahu Khayran,

Elias

**Comment by LDDConsulting** [comment]
This issue was resolved in the latest update.
