### ISSUE TITLE
Messed up display on WP theme

### ISSUE THREAD

**Issue by Lervia** [lddweb/ldd-directory-lite#83]
Hello guys

I love the directory plug in but it looks bad on Magazine theme , for example http://clickromania.co.uk/listing/ambasada-ungariei/

The footer is all over the place. any solutions to fix it ?

Thanks in advance

**Comment by Lervia** [comment]
Is there a solution ?

**Comment by LDDConsulting** [comment]
There is a conflict with some theme sidebars in our template files. For now you can resolve the issue by following these steps:

1. Create a new directory in your theme's folder ( /wp-content/themes/yourtheme/**lddlite_templates**/ )

2. Copy the template file “**single.php**" from **/wp-content/plugins/ldd-directory-lite/templates/** to the directory you just created (**lddlite_templates**)

3. On line #96 in the file "**single.php**" delete the following: `<?php get_sidebar(); ?>`
