### ISSUE TITLE
Plugin after activation it destructs the template and the fonts

### ISSUE THREAD

**Issue by marcus1er** [lddweb/ldd-directory-lite#85]
Hello, 

The plugin "LDD Directory Lite" is perfect. But after activation it destructs the template and the fonts. 
Files in your plugin replace the template files (Themeforest theme). 

I try the solution that is in the faq on website plugin, but it does not work. 

Thank you for your help.

**Comment by LDDConsulting** [comment]
We are supporting this issue currently on the WordPress support forum.
