### ISSUE TITLE
Manage & Submit Pages not displaying

### ISSUE THREAD

**Issue by aishaladon** [lddweb/ldd-directory-lite#86]
The plugin was working fine the other day. Now its not. 
I cant see the submit and manage pages on the front end. I have tried to active and reactive, Ive turned all other plugins off as well. Nothing works.

http://www.legacybhive.net/directory-2/

**Comment by LDDConsulting** [comment]
Did you check the settings of the plugin to see if this feature was turned off?
( Dashboard >Directory > Settings )

http://prntscr.com/f8ii9w

**Comment by aishaladon** [comment]
I guess I turned it off.
Thanks so much for the help

Aisha

Life is good, have a blessed day
Sincerely,
Aisha LaDon



www.legacydesignsstudio.com

**Comment by LDDConsulting** [comment]
Thanks for using our plugin. If you don't mind please also take a moment to rate us on WordPress.org (https://wordpress.org/support/plugin/ldd-directory-lite/reviews/)
