### ISSUE TITLE
have_posts() on a non-object

### ISSUE THREAD

**Issue by aptusmarketing** [lddweb/ldd-directory-lite#92]
Suddenly receiving the following error:

Fatal error: Call to a member function have_posts() on a non-object in /home/lifemin/public_html/wp-content/plugins/ldd-directory-lite/templates/category.php on line 158

on page ... http://freedomeveryday.org/support-groups/men-sex-addict-groups/ 

What does it mean? How do I fix it? Why did it happen?

TIA
Mr. B

**Comment by LDDConsulting** [comment]
This issue should have been fix now. could you please try our latest version?
