### ISSUE TITLE
Backend access given via directory_contributor 

### ISSUE THREAD

**Issue by pt23** [lddweb/ldd-directory-lite#95]
We are experiencing an issue whereby people who have listed in our directory - and therefore approved at directory_contributor - are getting more backend access than they should ... to posts, pages, comments and some plugins.

It looks like they're being given editor access or similar.

We ned contributors to be able to edit their listings but they mustn't have that level of backend access.

Are you aware of this and is there a fix?

Thanks, Paul

**Comment by LDDConsulting** [comment]
The issue should have been resolved in our latest beta version
